# .github/workflows/bento-ci.yml
name: CI/CD for BentoML Service

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Train Model
        run: |
          python train_model.py

      - name: Bento Build
        run: |
          bentoml build

      - name: Bento Containerize
        run: |
          bentoml containerize iris_classifier:latest

      # Optional: Push to DockerHub
      - name: Docker Login
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Push to DockerHub
        run: |
          docker tag iris_classifier:latest yourdockerhub/iris_classifier:latest
          docker push yourdockerhub/iris_classifier:latest
